name: Post Quote to Instagram

on:
  schedule:
    # Runs at 9 AM and 9 PM IST (3:30 AM and 3:30 PM UTC)
    - cron: '30 3,15 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-dejavu
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create instaPhotos directory
      run: mkdir -p instaPhotos

    - name: Setup authentication
      env:
        INSTA_USER: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTA_PASS: ${{ secrets.INSTAGRAM_PASSWORD }}
        UNSPLASH_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        INSTA_SESSION: ${{ secrets.INSTAGRAM_SESSION }}
      run: |
        # Create .env file
        echo "INSTAGRAM_USERNAME=${INSTA_USER}" >> .env
        echo "INSTAGRAM_PASSWORD=${INSTA_PASS}" >> .env
        echo "UNSPLASH_ACCESS_KEY=${UNSPLASH_KEY}" >> .env
        
        # Create Instagram session file from secret
        echo "${INSTA_SESSION}" > instagram_session.json

    - name: Run script
      run: python main.py

    - name: Clean up
      if: always()
      run: |
        rm -f instagram_session.json
        rm -rf instaPhotos/
